name: Class Rename

on:
    pull_request: null
    push: null

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: vendor/bin/rector process
